max_connections = 100
shared_buffers = 1024MB
effective_cache_size = 3584MB
maintenance_work_mem = 448MB
checkpoint_completion_target = 0.95
wal_buffers = 48MB
default_statistics_target = 150
random_page_cost = 2.9
effective_io_concurrency = 200
work_mem = 5120kB
huge_pages = off
min_wal_size = 3GB
max_wal_size = 4GB
max_worker_processes = 8
max_parallel_workers_per_gather = 7
max_parallel_workers = 8
max_parallel_maintenance_workers = 5
checkpoint_timeout = 20min
wal_compression = lz4
seq_page_cost = 0.5
jit = on
temp_buffers = 232MB
bgwriter_lru_maxpages = 350
bgwriter_delay = 200ms
