max_connections = 400
shared_buffers = 1536MB
effective_cache_size = 1536MB
maintenance_work_mem = 512MB
checkpoint_completion_target = 0.85
wal_buffers = 32MB
default_statistics_target = 125
random_page_cost = 3.9
effective_io_concurrency = 100
work_mem = 12288kB
huge_pages = off
min_wal_size = 2GB
max_wal_size = 16GB
max_worker_processes = 5
max_parallel_workers_per_gather = 1
max_parallel_workers = 5
max_parallel_maintenance_workers = 2
checkpoint_timeout = 20min
wal_compression = zstd
seq_page_cost = 1.0
jit = off
temp_buffers = 192MB
bgwriter_lru_maxpages = 300
bgwriter_delay = 450ms
