max_connections = 325
shared_buffers = 1280MB
effective_cache_size = 2GB
maintenance_work_mem = 512MB
checkpoint_completion_target = 0.7
wal_buffers = 48MB
default_statistics_target = 75
random_page_cost = 2.3
effective_io_concurrency = 350
work_mem = 3072kB
huge_pages = off
min_wal_size = 3GB
max_wal_size = 6GB
max_worker_processes = 6
max_parallel_workers_per_gather = 4
max_parallel_workers = 4
max_parallel_maintenance_workers = 3
checkpoint_timeout = 5min
