# ==========================================
# PostgreSQL Base Configuration
# ==========================================

# Network & Connections
listen_addresses = '*'
port = 5432
max_connections = 100
superuser_reserved_connections = 3

# Logging
log_destination = 'stderr'
logging_collector = off
log_statement = 'all'
log_min_duration_statement = 1000

# Startup Extensions (Requires restart to change)
shared_preload_libraries = 'pg_stat_statements'
pg_stat_statements.track = all
pg_stat_statements.max = 10000

# Include Performance Tweaks
include = '/etc/postgresql/conf/performance.conf'
